### PR TITLE
remove until fall damage

### PR DESCRIPTION
**Pull request by w4536p**
i think this does it but im not 100% sure from what i see ingame it works though

If your pull request is **not** translation or serverlist-related, read the list of requirements below and check each box:

- [x] I have read the [contribution guidelines](https://github.com/Anuken/Mindustry/blob/master/CONTRIBUTING.md).
- [x] I have ensured that my code compiles, if applicable.
- [x] I have ensured that any new features in this PR function correctly in-game, if applicable.

### CODE REVIEW

**Comment by fuzzbuck** [comment]
how about just adding (false &&) into the if check? it will maintain the original structure and do the same thing

**Comment by TranquillyUnpleasant** [comment]
Or make it work for the player team so it actually makes sense, in case theres td maps with pre built enemy defenses or whatever

**Comment by buthed010203** [comment]
> how about just adding (false &&) into the if check? it will maintain the original structure and do the same thing

Or you could just comment it out..

**Comment by fuzzbuck** [comment]
implemented

**Pull request closed without merging**
