### PR TITLE
Minor rehaul and a bunch of fixes

### PR DESCRIPTION
**Pull request by TranquillyUnpleasant**
10k in denominator = slower than linear scaling for 5k waves

You know that makes no sense

### CODE REVIEW

**Comment by fuzzbuck** [comment]
this doesnt make sense either,
250x on wave 500?

**Comment by fuzzbuck** [comment]
i suggest 6659
(it gives perfect 2x on wave 100)

**Comment by TranquillyUnpleasant** [comment]
More changes:
- 

> this doesnt make sense either,
> 250x on wave 500?

That is entirely reasonable, wave 500 is about 2 hours in on a fast map (15 second waves), on a slow one its as late as 5-6 hours in(30-40 second waves), you want games to last much longer than that?

Reminder that people used to literally infinite defend with a 100x capped multiplier when TD was a thing in v6, i had to go and add a stupid amount of shields to make maps viable.

**Comment by TranquillyUnpleasant** [comment]
Also other changes:
- Tutorial code is less of a mess
- Paths now check all tiles for placement so you cant block thin paths with exponential reconstructors
- Sharded non player units die after a proportional amount of time to their construction time, tier 1 units last 5 minutes, tier 2 last 10 mins, their 3 last 30 mins, tier 4 last 1.5 hours and tier 5 last 4 hours. This is literally just their construction time converted from seconds to minutes. Makes units actually cost something, and prevents spam a bit.

**Comment by fuzzbuck** [comment]
has the unit mechanic been thought out?

**Comment by fuzzbuck** [comment]
add the fact that unit kill themselves in the tutorial then?

**Comment by fuzzbuck** [comment]
can u test this?
afaik clients will have trouble joining a non existent (for them) gamemode

**Comment by TranquillyUnpleasant** [comment]
> can u test this?
> afaik clients will have trouble joining a non existent (for them) gamemode

Works fine, the gamemode name is from the assigned name and not the bundles thing, the bundles is only relevant if you compile TD to work as a client, but i figured might as well add it. The settings apply fine.

(p.s. This is also how flood sets enemy team and gamemode)

**Comment by TranquillyUnpleasant** [comment]
generified imports so they didnt have random conflicts

**Comment by fuzzbuck** [comment]
change multiplier division to 6659 and lets merge

**Comment by TranquillyUnpleasant** [comment]
6659 was still a bit slow, considering that current maps seem to be making extensive use of shields, or lasting like 8 hours before people get bored and rtv.
So i present 3175. The reason for the number is in the trade offer.

**Comment by TranquillyUnpleasant** [comment]
Yes i tested it.

**Pull request merged**
